export const metadata = {
  title: "Create T3 App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  slot,
  secondSlot,
}: {
  slot: React.ReactNode;
  secondSlot: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ display: "flex" }}>
        {slot}
        {secondSlot}
      </body>
    </html>
  );
}
